[package]
name = "xrtranslate-protocol"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
serde = { version = "1.0.229", features = ["derive"] }
xr-corpus-protocol = { path = "../../XR-Corpus/crates/protocol" }
xrtranslate-prompt = { path = "../xrtranslate-prompt" }
